namespace AlchemyRPG;

/// <summary>
/// Represents the physical game world. Handles the generation of the map grid, 
/// random item placement, collision detection, and rendering of the entire screen.
/// </summary>
public class Map
{
    public int Width { get; }
    public int Height { get; }

    /// <summary> 
    /// A 2D array representing the terrain ('█' for walls, ' ' for empty floor). 
    /// </summary>
    public char[,] Grid { get; }

    /// <summary> 
    /// A collection storing all items currently placed on the map along with their coordinates. 
    /// </summary>
    private readonly List<(int X, int Y, IItem Item)> _items = [];

    /// <summary>
    /// Initializes a new instance of the Map class.
    /// Calls the external Labyrinth generator and populates the map with initial items.
    /// </summary>
    public Map(int width, int height)
    {
        Width = width;
        Height = height;
        Grid = new char[height, width];
    }

    /// <summary>
    /// Explicitly places an item at the exact given coordinates. Commonly used when a player drops an item.
    /// </summary>
    public void PlaceItemAt(int x, int y, IItem item) => _items.Add((x, y, item));

    /// <summary> 
    /// Adds an item to the map's active tracking list. 
    /// </summary>
    public void AddItem(int x, int y, IItem item) => _items.Add((x, y, item));

    /// <summary> 
    /// Removes an item from the map, typically called when the player picks it up. 
    /// </summary>
    public void RemoveItem(int x, int y, IItem item) => _items.Remove((x, y, item));

    /// <summary>
    /// Retrieves all items currently located at the specified exact coordinates.
    /// </summary>
    /// <param name="x">The horizontal coordinate.</param>
    /// <param name="y">The vertical coordinate.</param>
    /// <returns>A list of items at the given position, or an empty list if none exist.</returns>
    public List<IItem> GetItemsAt(int x, int y) => [.. _items.Where(i => i.X == x && i.Y == y).Select(i => i.Item)];

    /// <summary>
    /// Determines whether a specific coordinate is safe for the player to walk on.
    /// Checks grid boundaries to prevent IndexOutOfRange exceptions and ensures the tile is not a wall.
    /// </summary>
    /// <param name="x">The target X coordinate.</param>
    /// <param name="y">The target Y coordinate.</param>
    /// <returns><c>true</c> if the coordinate is within bounds and walkable; otherwise, <c>false</c>.</returns>
    public bool IsWalkable(int x, int y)
    {
        if (x < 0 || x >= Width || y < 0 || y >= Height || Grid[y, x] == Tiles.Wall)
            return false;

        bool hasEnemy = GetItemsAt(x, y).OfType<Enemy>().Any();
        if (hasEnemy)
            return false;

        return true;
    }
    /// <summary>
    /// Renders the complete game screen frame by frame.
    /// Draws the map grid, player position, items, and the side/bottom panels.
    /// </summary>
    /// <param name="state">The current game state, providing access to player position and logs.</param>
    public void Draw(GameState state)
    {
        var p = state.Player;

        for (int y = 0; y < Height; y++)
        {
            string mapLine = $"{Tiles.Floor}";
            for (int x = 0; x < Width; x++)
            {
                if (x == p.X && y == p.Y) mapLine += Tiles.Player;
                else
                {
                    var itemsHere = GetItemsAt(x, y);
                    if (itemsHere.Count > 1)
                        mapLine += $"{Tiles.SeveralItems}";
                    else if (itemsHere.Count == 1)
                        mapLine += itemsHere.First().Symbol;
                    else
                        mapLine += Grid[y, x];
                }
            }

            string statsLine = GetStatsLine(y, p);
            Console.WriteLine($"{mapLine}   {statsLine}".PadRight(100));
        }

        Console.WriteLine("".PadRight(Config.PaddingRight));

        var standingOn = GetItemsAt(p.X, p.Y);
        string groundInfo;
        if (standingOn.Count > 1)
        {
            groundInfo = $"Ground: {standingOn.Count} items ({Tiles.SeveralItems}). Top: {standingOn.First().Name} (Press {Keybinds.PickUp} to loot)";
        }
        else if (standingOn.Count == 1)
        {
            groundInfo = $"Ground: {standingOn.First().Name} (Press {Keybinds.PickUp})";
        }
        else
        {
            groundInfo = "Ground: Empty";
        }
        Console.WriteLine(groundInfo.PadRight(Config.PaddingRight));

        Console.WriteLine($"Log: {state.Log} {p.LogMessage}".PadRight(Config.PaddingRight));
        p.LogMessage = "";

        // Displays the dynamic tutorial instructions generated by the DungeonBuilder.
        Console.WriteLine(state.Instructions.PadRight(Config.PaddingRight));
    }

    /// <summary>
    /// Generates the text for the right-side UI panel based on the current vertical rendering row.
    /// </summary>
    /// <param name="y">The current row (Y-coordinate) being drawn on the screen.</param>
    /// <param name="p">The player object containing the stats to display.</param>
    /// <returns>A formatted string representing a specific line of user interface.</returns>
    private static string GetStatsLine(int y, Player p)
    {
        return y switch
        {
            0 => "--- STATISTICS ---",
            1 => $"HP: {p.Health} | STR: {p.Strength} | DEX: {p.Dexterity}",
            2 => $"WIS: {p.Wisdom} | AGR: {p.Aggression} | LUCK: {p.Luck}",
            3 => $"Gold: {p.Gold} | Coins: {p.Coins}",
            5 => "--- HANDS ---",
            6 => $"Left: {(p.LeftHand?.Name ?? "Empty")}",
            7 => $"Right: {(p.RightHand?.Name ?? "Empty")}",
            9 => "--- INVENTORY ---",
            _ => (y >= 10 && y < 10 + p.Backpack.Count) ? $"[{y - 10}] {p.Backpack[y - 10].Name}" : ""
        };
    }
}