namespace AlchemyRPG;

/// <summary>
/// Represents a command to pick up the top-most item located on the player's current tile.
/// Handles item interaction, inventory management, and noise generation.
/// </summary>
public class PickUpCommand : ICommand
{
    /// <summary>
    /// Validates whether there is an item available to pick up at the executor's current position.
    /// </summary>
    public bool CanExecute(GameState state, Player executor)
    {
        if (executor.IsDead) return false;

        var items = state.Map.GetItemsAt(executor.X, executor.Y);
        if (items.Count == 0)
        {
            executor.SetLogMessage("Nothing to pick up here.");
            return false;
        }
        return true;
    }

    /// <summary>
    /// Executes the pick-up action. Retrieves the last added item from the tile, triggers its pickup logic,
    /// logs the event, and propagates any sound generated by the item interaction.
    /// </summary>
    public void Execute(GameState state, Player executor)
    {
        var items = state.Map.GetItemsAt(executor.X, executor.Y);
        
        if (items.Count > 0)
        {
            var item = items.Last();
            item.OnPickUp(state, executor);

            state.SystemLogs.Notify(new SystemLogData(LogType.Loot, $"{executor.Name} picked up {item.Name}"));
            state.EventLog.Push($"{executor.Name} picked up: {item.Name}");

            // Calculate noise range using the Visitor pattern to determine the sound propagation distance
            int noiseRange = item.Accept(new ItemNoiseVisitor());
            
            if (noiseRange > 0)
            {
                state.SystemLogs.Notify(new SystemLogData(LogType.Loot, $"Noise generated: {noiseRange}"));
                state.EventLog.Push($"{executor.Name} made noise (Range: {noiseRange})");

                // Propagate sound in the dungeon
                var acousticMap = state.Acoustic.CalculateAcousticDistances(state.Map, executor.X, executor.Y, noiseRange);
                var noiseData = new NoiseData(executor.X, executor.Y, acousticMap);
                state.NoiseEvents.Notify(noiseData);
            }
        }
    }
}