namespace AlchemyRPG;

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

/// <summary>
/// A lightweight representation of an inventory item utilized for network transmission.
/// </summary>
public class InventorySlotDTO
{
    public Guid Id { get; set; }
    public string Name { get; set; } = "";
}

/// <summary>
/// Represents the complete state of the game customized for a specific connected client.
/// Sent by the server during every game tick if changes occur.
/// </summary>
public class GameStateDTO
{
    public required MapDTO Map { get; set; }

    /// <summary>The data for the specific player receiving this DTO.</summary>
    public required PlayerDTO LocalPlayer { get; set; }

    /// <summary>Data representing all other active players in the session, excluding the local player.</summary>
    public List<PlayerDTO> OtherPlayers { get; set; } = new();

    /// <summary>A list of recent action logs formatted for the local UI.</summary>
    public List<string> RecentEvents { get; set; } = new();

    /// <summary>The complete historical log of the game session for the Journal view.</summary>
    public List<string> FullJournal { get; set; } = new();
}

/// <summary>
/// Represents the physical state of the dungeon map and its dynamic contents.
/// </summary>
public class MapDTO
{
    public int Width { get; set; }
    public int Height { get; set; }
    public List<ItemDTO> Items { get; set; } = new();
    public List<EntityDTO> Enemies { get; set; } = new();
}

/// <summary>
/// Represents a non-player entity (like an enemy) on the map.
/// </summary>
public class EntityDTO
{
    public int X { get; set; }
    public int Y { get; set; }
    public string Name { get; set; } = "";
    public int Health { get; set; }
}

/// <summary>
/// Represents a player's complete state, including coordinates, RPG statistics, and inventory.
/// </summary>
public class PlayerDTO
{
    public int Id { get; set; }
    public int X { get; set; }
    public int Y { get; set; }
    public string Name { get; set; } = "";
    public int Health { get; set; }

    // RPG Statistics
    public int Strength { get; set; }
    public int Dexterity { get; set; }
    public int Wisdom { get; set; }
    public int Aggression { get; set; }
    public int TotalLuck { get; set; }

    // Currency
    public int Gold { get; set; }
    public int Coins { get; set; }

    // Inventory and Equipment
    public List<InventorySlotDTO> Backpack { get; set; } = new();
    public string LeftHandName { get; set; } = "Empty";
    public string RightHandName { get; set; } = "Empty";
    public List<string> BackpackItemNames { get; set; } = new();

    /// <summary>A localized feedback message generated by the server for this player's previous action.</summary>
    public string LogMessage { get; set; } = "";
}

/// <summary>
/// Defines a contract for the Visitor design pattern applied to network Item DTOs.
/// Used extensively by the client view to determine rendering logic (e.g., choosing ASCII symbols).
/// </summary>
public interface IItemDTOVisitor<T>
{
    T VisitWeapon(WeaponDTO dto);
    T VisitGold(GoldDTO dto);
    T VisitCoin(CoinDTO dto);
    T VisitJunk(JunkDTO dto);
}

/// <summary>
/// The abstract base class for all interactable items sent over the network.
/// Implements polymorphic JSON serialization attributes to ensure exact type recovery during deserialization.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "Type")]
[JsonDerivedType(typeof(WeaponDTO), typeDiscriminator: "Weapon")]
[JsonDerivedType(typeof(GoldDTO), typeDiscriminator: "Gold")]
[JsonDerivedType(typeof(CoinDTO), typeDiscriminator: "Coin")]
[JsonDerivedType(typeof(JunkDTO), typeDiscriminator: "Junk")]
public abstract class ItemDTO
{
    public int X { get; set; }
    public int Y { get; set; }
    public string Name { get; set; } = "";
    public abstract T Accept<T>(IItemDTOVisitor<T> visitor);
}

public class WeaponDTO : ItemDTO { public override T Accept<T>(IItemDTOVisitor<T> v) => v.VisitWeapon(this); }
public class GoldDTO : ItemDTO { public override T Accept<T>(IItemDTOVisitor<T> v) => v.VisitGold(this); }
public class CoinDTO : ItemDTO { public override T Accept<T>(IItemDTOVisitor<T> v) => v.VisitCoin(this); }
public class JunkDTO : ItemDTO { public override T Accept<T>(IItemDTOVisitor<T> v) => v.VisitJunk(this); }

/// <summary>
/// Contains heavy, static initialization data sent to a client immediately upon connection.
/// Contains the terrain layout and overarching game rules, minimizing data transfer in subsequent updates.
/// </summary>
public class InitialDataDTO
{
    /// <summary>The static layout of walls and floors.</summary>
    public required string[] Grid { get; set; }

    /// <summary>The quick-reference controls for the UI footer.</summary>
    public string Instructions { get; set; } = "";

    /// <summary>The extensive tutorial and lore text shown on the welcome screen.</summary>
    public string TutorialText { get; set; } = "";
}